Include /etc/coraza/crs-setup.conf
Include /etc/coraza/rules/*.conf

SecRuleEngine On
SecRequestBodyAccess On
SecResponseBodyAccess Off

# Proxy to internal Nginx
ProxyPass "/" "http://nginx:80/"
ProxyPassReverse "/" "http://nginx:80/"