[ place in /etc/ssh/sshd_config.d/ ]
UsePAM yes
PubkeyAuthentication yes
PasswordAuthentication no
PermitEmptyPasswords no
PermitRootLogin no
ChallengeResponseAuthentication no
AllowUsers kaloed grafanaport
Match User grafanaport
    AllowTcpForwarding yes
    PermitTTY no
    X11Forwarding no
    ForceCommand /bin/false
    MaxSessions 1
    ChallengeResponseAuthentication yes
    AuthenticationMethods publickey,keyboard-interactive
