# server {
#     listen 80;
#     server_name kuban-govnovoz.space;

#     location /.well-known/acme-challenge/ {
#         root /var/www/certbot;
#     }

#     location / {
#         return 301 https://\$host\$request_uri;
#     }
# }

# server {
#     listen 8443 ssl;
#     server_name kuban-govnovoz.space;

#     ssl_certificate     /etc/letsencrypt/live/kuban-govnovoz.space/fullchain.pem;
#     ssl_certificate_key /etc/letsencrypt/live/kuban-govnovoz.space/privkey.pem;

#     ssl_protocols TLSv1.2 TLSv1.3;
#     ssl_prefer_server_ciphers on;

#     location / {
#         root /usr/share/nginx/html;
#         index index.html;
#     }
# }
stream {
    upstream telegram_backend {
        # Основные дата-центры Telegram (DC2, DC4, DC5)
        server 149.154.167.50:443;
        server 149.154.167.51:443;
        server 149.154.175.100:443;
        server 149.154.167.91:443;
        server 95.161.76.100:443;
        # Добавьте другие при необходимости
        keepalive 32;
    }

    server {
        listen 8443 ssl;
        ssl_certificate /etc/letsencrypt/live/kuban-govnovoz.space/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/kuban-govnovoz.space/privkey.pem;
        ssl_protocols TLSv1.2 TLSv1.3;
        proxy_pass telegram_backend;
        proxy_ssl on;
        proxy_ssl_protocols TLSv1.2 TLSv1.3;
        proxy_timeout 5m;
    }
}